import { IWinningNumber, IGameData, IMonitorData, IRoundStatus } from './redux/types'

export const API_ENDPOINT = '//ag-dealer-server.azurewebsites.net'
export const SOCKET_ENDPOINT = API_ENDPOINT + '/ta'
export const STATUS_API_ENDPOINT = '//json.itsreal.live/info/status/live/studio-roulette2'


export const APPLICATION_TYPE: { [status: string]: string } = {
  'tablet': 'game',
  'monitor': 'monitor',
  'activity': 'activity',
}

export const MANUAL_ACTIONS = {
  CANCEL: 'Cancel',
  PAUSE: 'Pause',
  SUSPEND: 'Suspend',
}

export const ROUND_STATUS: { [status: string]: IRoundStatus } = {
  'NEWGAME': {
    text: 'Place Bets',
    colour: 'green',
  },
  'BETTIME': {
    text: 'Place Bets',
    colour: 'green',
  },
  'LASTBET': {
    text: 'Final Bets',
    colour: 'yellow',
  },
  'NOMOREBET': {
    text: 'No More Bets',
    colour: 'red',
  },
  'WINNUMBER': {
    text: 'Reveal Phase',
    colour: 'yellow',
  },
  'SUSPEND': {
    text: 'Round Suspended',
    colour: 'red',
  },
  'CANCELGAME': {
    text: 'Round Cancelled',
    colour: 'red',
  },
}

export const winningNumberSectorMap: { [number: string]: IWinningNumber } = {
  '0': {
    number: '0',
    colour: '',
    lowHigh: '',
    evenOdd: '',
    column: '',
    dozen: '',
    section: 'voisins',
  },
  '1': {
    number: '1',
    colour: 'red',
    lowHigh: 'low',
    evenOdd: 'odd',
    column: '1st',
    dozen: '1st',
    section: 'orphelins',
  },
  '2': {
    number: '2',
    colour: 'black',
    lowHigh: 'low',
    evenOdd: 'even',
    column: '2nd',
    dozen: '1st',
    section: 'voisins',
  },
  '3': {
    number: '3',
    colour: 'red',
    lowHigh: 'low',
    evenOdd: 'odd',
    column: '3rd',
    dozen: '1st',
    section: 'voisins',
  },
  '4': {
    number: '4',
    colour: 'black',
    lowHigh: 'low',
    evenOdd: 'even',
    column: '1st',
    dozen: '1st',
    section: 'voisins',
  },
  '5': {
    number: '5',
    colour: 'red',
    lowHigh: 'low',
    evenOdd: 'odd',
    column: '2nd',
    dozen: '1st',
    section: 'tier',
  },
  '6': {
    number: '6',
    colour: 'black',
    lowHigh: 'low',
    evenOdd: 'even',
    column: '3rd',
    dozen: '1st',
    section: 'orphelins',
  },
  '7': {
    number: '7',
    colour: 'red',
    lowHigh: 'low',
    evenOdd: 'odd',
    column: '1st',
    dozen: '1st',
    section: 'voisins',
  },
  '8': {
    number: '8',
    colour: 'black',
    lowHigh: 'low',
    evenOdd: 'even',
    column: '2nd',
    dozen: '1st',
    section: 'tier',
  },
  '9': {
    number: '9',
    colour: 'red',
    lowHigh: 'low',
    evenOdd: 'odd',
    column: '3rd',
    dozen: '1st',
    section: 'orphelins',
  },
  '10': {
    number: '10',
    colour: 'black',
    lowHigh: 'low',
    evenOdd: 'even',
    column: '1st',
    dozen: '1st',
    section: 'tier',
  },
  '11': {
    number: '11',
    colour: 'black',
    lowHigh: 'low',
    evenOdd: 'odd',
    column: '2nd',
    dozen: '1st',
    section: 'tier',
  },
  '12': {
    number: '12',
    colour: 'red',
    lowHigh: 'low',
    evenOdd: 'even',
    column: '3rd',
    dozen: '1st',
    section: 'voisins',
  },
  '13': {
    number: '13',
    colour: 'black',
    lowHigh: 'low',
    evenOdd: 'odd',
    column: '1st',
    dozen: '2nd',
    section: 'tier',
  },
  '14': {
    number: '14',
    colour: 'red',
    lowHigh: 'low',
    evenOdd: 'even',
    column: '2nd',
    dozen: '2nd',
    section: 'orphelins',
  },
  '15': {
    number: '15',
    colour: 'black',
    lowHigh: 'low',
    evenOdd: 'odd',
    column: '3rd',
    dozen: '2nd',
    section: 'voisins',
  },
  '16': {
    number: '16',
    colour: 'red',
    lowHigh: 'low',
    evenOdd: 'even',
    column: '1st',
    dozen: '2nd',
    section: 'tier',
  },
  '17': {
    number: '17',
    colour: 'black',
    lowHigh: 'low',
    evenOdd: 'odd',
    column: '2nd',
    dozen: '2nd',
    section: 'orphelins',
  },
  '18': {
    number: '18',
    colour: 'red',
    lowHigh: 'low',
    evenOdd: 'even',
    column: '3rd',
    dozen: '2nd',
    section: 'voisins',
  },
  '19': {
    number: '19',
    colour: 'red',
    lowHigh: 'high',
    evenOdd: 'odd',
    column: '1st',
    dozen: '2nd',
    section: 'voisins',
  },
  '20': {
    number: '20',
    colour: 'black',
    lowHigh: 'high',
    evenOdd: 'even',
    column: '2nd',
    dozen: '2nd',
    section: 'orphelins',
  },
  '21': {
    number: '21',
    colour: 'red',
    lowHigh: 'high',
    evenOdd: 'odd',
    column: '3rd',
    dozen: '2nd',
    section: 'voisins',
  },
  '22': {
    number: '22',
    colour: 'black',
    lowHigh: 'high',
    evenOdd: 'even',
    column: '1st',
    dozen: '2nd',
    section: 'voisins',
  },
  '23': {
    number: '23',
    colour: 'red',
    lowHigh: 'high',
    evenOdd: 'odd',
    column: '2nd',
    dozen: '2nd',
    section: 'tier',
  },
  '24': {
    number: '24',
    colour: 'black',
    lowHigh: 'high',
    evenOdd: 'even',
    column: '3rd',
    dozen: '2nd',
    section: 'tier',
  },
  '25': {
    number: '25',
    colour: 'red',
    lowHigh: 'high',
    evenOdd: 'odd',
    column: '1st',
    dozen: '3rd',
    section: 'voisins',
  },
  '26': {
    number: '26',
    colour: 'black',
    lowHigh: 'high',
    evenOdd: 'even',
    column: '2nd',
    dozen: '3rd',
    section: 'voisins',
  },
  '27': {
    number: '27',
    colour: 'red',
    lowHigh: 'high',
    evenOdd: 'odd',
    column: '3rd',
    dozen: '3rd',
    section: 'tier',
  },
  '28': {
    number: '28',
    colour: 'red',
    lowHigh: 'high',
    evenOdd: 'even',
    column: '1st',
    dozen: '3rd',
    section: 'voisins',
  },
  '29': {
    number: '29',
    colour: 'black',
    lowHigh: 'high',
    evenOdd: 'odd',
    column: '2nd',
    dozen: '3rd',
    section: 'voisins',
  },
  '30': {
    number: '30',
    colour: 'red',
    lowHigh: 'high',
    evenOdd: 'even',
    column: '3rd',
    dozen: '3rd',
    section: 'tier',
  },
  '31': {
    number: '31',
    colour: 'black',
    lowHigh: 'high',
    evenOdd: 'odd',
    column: '1st',
    dozen: '3rd',
    section: 'orphelins',
  },
  '32': {
    number: '32',
    colour: 'red',
    lowHigh: 'high',
    evenOdd: 'even',
    column: '2nd',
    dozen: '3rd',
    section: 'voisins',
  },
  '33': {
    number: '33',
    colour: 'black',
    lowHigh: 'high',
    evenOdd: 'odd',
    column: '3rd',
    dozen: '3rd',
    section: 'tier',
  },
  '34': {
    number: '34',
    colour: 'red',
    lowHigh: 'high',
    evenOdd: 'even',
    column: '1st',
    dozen: '3rd',
    section: 'orphelins',
  },
  '35': {
    number: '35',
    colour: 'black',
    lowHigh: 'high',
    evenOdd: 'odd',
    column: '2nd',
    dozen: '3rd',
    section: 'voisins',
  },
  '36': {
    number: '36',
    colour: 'red',
    lowHigh: 'high',
    evenOdd: 'even',
    column: '3rd',
    dozen: '3rd',
    section: 'tier',
  },
}

export const DEFAULT_GAME_DATA: IGameData = {
  roundStatus: '',
  roundTimeTotal: '0',
  roundTimeLeft: '0',
  winningNumber: '0',
  stopReason: '',
  errorCode: '',
  casino: '',
  type: '',
  device: '',
  timestamp: 0,
}

export const DEFAULT_MONITOR_DATA: IMonitorData = {
  status: '',
  roundStatus: '',
  winningNumber: '',
  wheelStatus: '',
  wheelSpeed: '',
  ballLauchSpeed: '',
  revolutionsCount: '',
  wheelId: '',
  casino: '',
  type: '',
  device: '',
  timestamp: 0,
  roundId: '',
  errorFlag: '',
}
